### ISSUE TITLE
More language

### ISSUE THREAD

**Issue by Dobby233Liu** [Dobby233Liu/yvdcover#2]
- [x] A language system
- [x] Simplified Chinese
- [x] Traditional Chinese
- [x] And of course add a language selector in the footer/navbar

**Comment by atj393** [comment]
Hi @Dobby233Liu ,
Happy to meet you.
Can you please comment on what is SC and TC?

Thanks.

**Comment by Dobby233Liu** [comment]
> Hi @Dobby233Liu ,
> Happy to meet you.
> Can you please comment on what is SC and TC?
> 
> Thanks.

ok
and if you can localize i can assign you to it

**Comment by Dobby233Liu** [comment]
Language system was complete, but the footer text was not changed
!!notice: bug!!
