### ISSUE TITLE
Support Bilibili's BV video number format

### ISSUE THREAD

**Issue by wzxyisme** [Dobby233Liu/yvdcover#6]
bilibili recently started to promote the latest video number format bv.The bv prefix is ​​BV / bv, followed by a 10-digit string containing randomly generated upper and lower case letters (sensitive) and numbers.
The announcement is [here](https://www.bilibili.com/read/cv5167957)
Want update compatible

**Comment by Dobby233Liu** [comment]
I already knew this, but forgetten to update yvdcover. I'll get touch of this repo tomorrow (GMT+8).

**Comment by wzxyisme** [comment]
Thank you very much.

**Comment by wzxyisme** [comment]
都是中国人。。。(￣_￣|||)

**Comment by Dobby233Liu** [comment]
> 都是中国人。。。(￣_￣|||)

I write English too much on GitHub, so I'm nearly writting English in every English website. Sorry if I confused you.

**Comment by wzxyisme** [comment]
> > 都是中国人。。。(￣_￣|||)
> 
> I write English too much on GitHub, so I'm nearly writting English in every English website. Sorry if I confused you.

No problem

**Comment by Dobby233Liu** [comment]
More BV tech info on [Zhihu](https://www.zhihu.com/question/381784377). mcfx given a sample BV number. I have mcfx's parser converted to JS<del>, but it's useless anyway</del>.

**Comment by Dobby233Liu** [comment]
(mostly) done. Please test if it works right (https://d2lghp.ml/yvdcover).

**Comment by Dobby233Liu** [comment]
staled, closing
